export const PROJECTS_FETCHED_SUCCESS = 'PROJECTS_FETCHED_SUCCESS';
export const PROJECT_FETCHED_SUCCESS = 'PROJECT_FETCHED_SUCCESS';
export const PROJECT_ACTIVE_SUCCESS = 'PROJECT_ACTIVE_SUCCESS';
export const SIDE_BAR_SHOWN_SUCCESS = 'SIDE_BAR_SHOWN_SUCCESS';
