export const PROJECTS_FETCHED_SUCCESS = 'PROJECTS_FETCHED_SUCCESS';
export const PROJECT_FETCHED_SUCCESS = 'PROJECT_FETCHED_SUCCESS';
export const PROJECT_ACTIVE_SUCCESS = 'PROJECT_ACTIVE_SUCCESS';
export const SIDE_BAR_HANDLE_SUCCESS = 'SIDE_BAR_HANDLE_SUCCESS';

export const SOCIAL_LINKS_FETCHED_SUCCESS = 'SOCIAL_LINKS_FETCHED_SUCCESS';

export const BIO_FETCHED_SUCCESS = 'BIO_FETCHED_SUCCESS';
